# copied from https://github.com/binder-examples/python-conda_pip/blob/master/environment.yml
name: example-environment
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - cudatoolkit=11.0
  - pytorch==1.8.0
  - pandas
  - scikit-learn 
  - pip
  - pip:
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
    - torchvision==0.9.0
    - ogb==1.2.6
    - torch-geometric==1.6.1
    - pillow==7.2.0
    - pytz==2020.4
    - tqdm==4.53.0
    - wilds==1.1.0
    - opencv-python
    - matplotlib
    - outdated==0.2.0

