# copied from https://github.com/binder-examples/python-conda_pip/blob/master/environment.yml
name: example-environment
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - cudatoolkit=11.0
  - pytorch==1.8.0
  - pip
  - pip:
    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html
    - torchvision==0.9.0
    - ogb==1.2.6
    - torch-geometric
    - pandas
    - pillow
    - pytz
    - tqdm
    - wilds
    - scikit-learn
    - opencv-python
    - matplotlib

